### ISSUE TITLE
Cant Figure out how to ride it

### ISSUE THREAD

**Issue by NealSavage** [y2k04/cbp#2]
What is the "use button"? I changed the button that pairs with whatever is the use button to the backspace key to make sure it wasnt because of conflicts. I've tried backspace + left click, backspace + right click, and backspace + e. How do I ride my boat?

**Comment by y2k04** [comment]
You ride the boat by holding down your crouch button and interact button (the one you use to normally open things like Crafting Tables for example)

**Comment by y2k04** [comment]
By default, those buttons would be Left Alt and Left Click
