### ISSUE TITLE
Can't exit boat when key set to LSHIFT

### ISSUE THREAD

**Issue by MeeniMc** [y2k04/cbp#3]
If the 'ride' modifier key is changed from 'LALT' to 'LSHIFT', it is impossible to exit a boat.

**Comment by y2k04** [comment]
That is because LSHIFT is used to exit the boat in the first place. It is like entering and exiting the boat at the same time. It just cancels each other out and just causes nothing to happen.

**Comment by MeeniMc** [comment]
Not sure the explanation matches the problem here: entering works just fine, its existing that doesn't work.

**Comment by y2k04** [comment]
> Not sure the explanation matches the problem here: entering works just fine, its existing that doesn't work. 

I know. And that is something I cannot fix because of how vehicles work.
